# 线上配置文件
server:
  port: 8105
  servlet:
    context-path: /api/scoringResult
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: bbg-backend-scoring-service
  cloud:
      nacos:
      discovery:
        server-addr: nacos:8848
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/bbg
    username: root
    password: iKcS462jjp2MPbmW
  shardingsphere:
    #数据源配置
    datasource:
      # 多数据源以逗号隔开即可
      names: master
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/bbg
        username: root
        password: iKcS462jjp2MPbmW
    # 规则配置
    rules:
      sharding:
        # 分片算法配置
        sharding-algorithms:
          # 自定义分片规则名
          user-table-inline:
            ## inline 类型是简单的配置文件里面就能写的类型，其他还有自定义类等等
            type: INLINE
            props:
              algorithm-expression: user_$->{id % 2}
        tables:
          user:
            actual-data-nodes: master.user_$->{0..1}
            # 分表策略
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: user-table-inline
  # Redis 配置
  # 需替换配置，然后取消注释
  redis:
    database: 0
    host: redis
    port: 6379
    timeout: 5000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
ai:
  apiKey: sk-d749b0af4eec4b0a9f7e6ca41fa0a7f2
  model: qwen-plus
knife4j:
  enable: true
