version: '3'
services:
  mysql:
    image: mysql:8
    container_name: bbg-mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./.mysql-data:/var/lib/mysql # 持久化
    environment:
      MYSQL_DATABASE: bbg # 数据库名称
      MYSQL_USER: bbg # 用户名
      MYSQL_PASSWORD: iKcS462jjp2MPbmW
  redis:
    image: redis:7
    container_name: bbg-redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - ./.redis-data:/data # 持久化
  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: bbg-nacos
    ports:
      - "8848:8848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - mynetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
networks:
  mynetwork: