version: '3'
services:
  mysql:
    image: mysql:8
    container_name: bbg-mysql
    environment:
      MYSQL_ROOT_PASSWORD: iKcS462jjp2MPbmW # root 密码
      MYSQL_USER: bbg # 用户名
      MYSQL_PASSWORD: iKcS462jjp2MPbmW # 该用户的密码
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - mynetwork # 指定网络
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7
    container_name: bbg-redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - ./.redis-data:/data # 持久化

  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: bbg-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - mynetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=root
      - MYSQL_PASSWORD=iKcS462jjp2MPbmW
      - LANG=C.UTF-8
    depends_on:
      mysql:
        condition: service_healthy
    restart: always # 崩溃后自动重启


networks:
  mynetwork: